// <auto-generated />
using System;
using AppDeMensagem.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppDeMensagem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717141550_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppDeMensagem.Domain.Entity.Chat", b =>
                {
                    b.Property<Guid>("Chat_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("ChatType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.HasKey("Chat_ID");

                    b.ToTable("Chats", (string)null);

                    b.HasDiscriminator<string>("ChatType").HasValue("Chat");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AppDeMensagem.Domain.Entity.Message", b =>
                {
                    b.Property<Guid>("Message_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Chat_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SendTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Sender_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.HasKey("Message_ID");

                    b.HasIndex("Chat_ID");

                    b.HasIndex("Sender_ID");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("AppDeMensagem.Domain.Entity.UserChat", b =>
                {
                    b.Property<Guid>("UserChat_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Chat_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<Guid>("User_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserChat_ID");

                    b.HasIndex("Chat_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("UsersChat", (string)null);
                });

            modelBuilder.Entity("AppDeMensagem.Domain.Entity.Usuario", b =>
                {
                    b.Property<Guid>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Name");

                    b.Property<string>("UserProfile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_ID");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AppDeMensagem.Domain.Entity.ChatGroup", b =>
                {
                    b.HasBaseType("AppDeMensagem.Domain.Entity.Chat");

                    b.HasDiscriminator().HasValue("Group");
                });

            modelBuilder.Entity("AppDeMensagem.Domain.Entity.ChatPrivate", b =>
                {
                    b.HasBaseType("AppDeMensagem.Domain.Entity.Chat");

                    b.HasDiscriminator().HasValue("Private");
                });

            modelBuilder.Entity("AppDeMensagem.Domain.Entity.Message", b =>
                {
                    b.HasOne("AppDeMensagem.Domain.Entity.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("Chat_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppDeMensagem.Domain.Entity.UserChat", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("Sender_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("AppDeMensagem.Domain.Entity.UserChat", b =>
                {
                    b.HasOne("AppDeMensagem.Domain.Entity.Chat", "Chat")
                        .WithMany("UsersChat")
                        .HasForeignKey("Chat_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppDeMensagem.Domain.Entity.Usuario", "Usuario")
                        .WithMany("UsersChat")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppDeMensagem.Domain.Entity.Chat", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("UsersChat");
                });

            modelBuilder.Entity("AppDeMensagem.Domain.Entity.UserChat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AppDeMensagem.Domain.Entity.Usuario", b =>
                {
                    b.Navigation("UsersChat");
                });
#pragma warning restore 612, 618
        }
    }
}
