@AppDeMensagem.WebApi_HostAddress = http://localhost:5160

POST {{AppDeMensagem.WebApi_HostAddress}}/teste/
Accept: application/json
{
  "email": "william@gmail.com",
  "nome": "William José",
  "senha": "213"
}
###
